-- ==========================================
--  Minecraft Voice Chat — MySQL Schema
--  Compatible with MySQL 8.0+ / MariaDB 10.5+
-- ==========================================

CREATE DATABASE IF NOT EXISTS `vc_minecraft`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE `vc_minecraft`;

-- ------------------------------------------
-- Players: persistent settings per UUID
-- ------------------------------------------
CREATE TABLE IF NOT EXISTS `players` (
  `id`              INT UNSIGNED     NOT NULL AUTO_INCREMENT,
  `uuid`            CHAR(36)         NOT NULL,
  `username`        VARCHAR(16)      NOT NULL,
  `edition`         ENUM('java','bedrock') NOT NULL DEFAULT 'java',
  `role`            ENUM('player','vip','staff','admin') NOT NULL DEFAULT 'player' COMMENT 'Permission role',
  `mic_gain`        FLOAT            NOT NULL DEFAULT 1.0    COMMENT 'Input gain 0.0–2.0',
  `output_gain`     FLOAT            NOT NULL DEFAULT 1.0    COMMENT 'Output gain 0.0–2.0',
  `voice_range`     FLOAT            NOT NULL DEFAULT 32.0   COMMENT 'Voice range override in blocks',
  `is_muted`        TINYINT(1)       NOT NULL DEFAULT 0,
  `is_deafened`     TINYINT(1)       NOT NULL DEFAULT 0,
  `noise_suppression` TINYINT(1)     NOT NULL DEFAULT 1,
  `echo_cancellation` TINYINT(1)     NOT NULL DEFAULT 1,
  `auto_gain_control` TINYINT(1)     NOT NULL DEFAULT 1,
  `ptt_enabled`     TINYINT(1)       NOT NULL DEFAULT 0,
  `ptt_key`         VARCHAR(32)      NOT NULL DEFAULT 'CapsLock',
  `deafen_key`      VARCHAR(32)      NOT NULL DEFAULT 'F10',
  `mute_key`        VARCHAR(32)      NOT NULL DEFAULT 'F11',
  `device_input_id` VARCHAR(256)     NULL      DEFAULT NULL  COMMENT 'MediaDevices deviceId',
  `device_output_id` VARCHAR(256)    NULL      DEFAULT NULL,
  `theme`           VARCHAR(32)      NOT NULL DEFAULT 'dark',
  `force_muted`     TINYINT(1)       NOT NULL DEFAULT 0      COMMENT 'Admin force mute',
  `total_talk_seconds` BIGINT UNSIGNED NOT NULL DEFAULT 0   COMMENT 'Cumulative voice time',
  `mute_count`      INT UNSIGNED     NOT NULL DEFAULT 0      COMMENT 'Times muted by admin',
  `session_count`   INT UNSIGNED     NOT NULL DEFAULT 0      COMMENT 'Total voice sessions',
  `created_at`      DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`      DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_uuid` (`uuid`),
  INDEX `idx_username` (`username`),
  INDEX `idx_role` (`role`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------
-- Sessions: time-limited tokens generated by plugin
-- ------------------------------------------
CREATE TABLE IF NOT EXISTS `sessions` (
  `id`          INT UNSIGNED  NOT NULL AUTO_INCREMENT,
  `uuid`        CHAR(36)      NOT NULL,
  `username`    VARCHAR(16)   NOT NULL,
  `token`       CHAR(64)      NOT NULL,
  `server_id`   VARCHAR(64)   NOT NULL DEFAULT 'default',
  `ws_connected` TINYINT(1)  NOT NULL DEFAULT 0,
  `ip_address`  VARCHAR(45)   NULL,
  `created_at`  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `expires_at`  DATETIME      NOT NULL,
  `revoked`     TINYINT(1)    NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_uuid_server` (`uuid`, `server_id`),
  UNIQUE KEY `uq_token` (`token`),
  INDEX `idx_expires` (`expires_at`),
  INDEX `idx_uuid` (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------
-- Voice Rooms: one per server (or per world)
-- ------------------------------------------
CREATE TABLE IF NOT EXISTS `voice_rooms` (
  `id`          INT UNSIGNED  NOT NULL AUTO_INCREMENT,
  `room_key`    VARCHAR(128)  NOT NULL COMMENT 'Format: server_id:world_name',
  `server_id`   VARCHAR(64)   NOT NULL,
  `world_name`  VARCHAR(64)   NOT NULL DEFAULT 'world',
  `is_active`   TINYINT(1)   NOT NULL DEFAULT 1,
  `player_count` INT UNSIGNED NOT NULL DEFAULT 0,
  `created_at`  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_room_key` (`room_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------
-- Player Positions: latest position snapshot
-- ------------------------------------------
CREATE TABLE IF NOT EXISTS `player_positions` (
  `uuid`        CHAR(36)      NOT NULL,
  `server_id`   VARCHAR(64)   NOT NULL,
  `world`       VARCHAR(64)   NOT NULL DEFAULT 'world',
  `x`           DOUBLE        NOT NULL DEFAULT 0,
  `y`           DOUBLE        NOT NULL DEFAULT 64,
  `z`           DOUBLE        NOT NULL DEFAULT 0,
  `updated_at`  DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`uuid`, `server_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------
-- Session History: analytics / audit log
-- ------------------------------------------
CREATE TABLE IF NOT EXISTS `session_history` (
  `id`          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid`        CHAR(36)        NOT NULL,
  `username`    VARCHAR(16)     NOT NULL,
  `server_id`   VARCHAR(64)     NOT NULL,
  `join_time`   DATETIME        NOT NULL,
  `leave_time`  DATETIME        NULL,
  `duration_s`  INT UNSIGNED    NULL COMMENT 'Session duration in seconds',
  PRIMARY KEY (`id`),
  INDEX `idx_uuid` (`uuid`),
  INDEX `idx_server` (`server_id`),
  INDEX `idx_join_time` (`join_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------
-- Voice Activity Log: audit trail
-- ------------------------------------------
CREATE TABLE IF NOT EXISTS `voice_activity_log` (
  `id`          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid`        CHAR(36)        NOT NULL,
  `username`    VARCHAR(16)     NOT NULL,
  `action`      VARCHAR(32)     NOT NULL COMMENT 'joined|left|muted|unmuted|deafened|kicked|force_muted|role_changed',
  `metadata`    JSON            NULL      COMMENT 'Additional context (actor, reason, etc.)',
  `server_id`   VARCHAR(64)     NOT NULL DEFAULT 'default',
  `created_at`  DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_uuid` (`uuid`),
  INDEX `idx_action` (`action`),
  INDEX `idx_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------
-- Discord Account Links
-- ------------------------------------------
CREATE TABLE IF NOT EXISTS `discord_links` (
  `uuid`        CHAR(36)        NOT NULL,
  `discord_id`  VARCHAR(32)     NOT NULL,
  `discord_tag` VARCHAR(64)     NULL      COMMENT 'Username#discriminator or username',
  `linked_at`   DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`uuid`),
  UNIQUE KEY `uq_discord` (`discord_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------
-- Cleanup Event: remove expired sessions nightly
-- ------------------------------------------
DROP EVENT IF EXISTS `cleanup_expired_sessions`;
CREATE EVENT `cleanup_expired_sessions`
  ON SCHEDULE EVERY 1 HOUR
  DO DELETE FROM `sessions` WHERE `expires_at` < NOW() OR `revoked` = 1;
